Fix issue with blown integers
DEFRA/charging-module-api pull request #120
Opened 2020-10-16 16:07 UTC by Cruikshanks

https://trello.com/c/RIATlpAS

We had a report of a large bill run never returning a bill run summary from the WRLS team. The bill run in question had

- 9,658 transactions
- 2,684 customers

Initially it was thought to be the shear number of transactions (we had only tested up to 5K transactions at this point). But after some local testing we tracked the problem down to the values generated. In this case the total was more than £22 million.

It's good practise when you need to record money you do so as pence **not** pounds and pence. This nullifies any issues when you come to start performing calculations. The problem for us was the fields in the database had been set as integers. In PostgreSQL the min and max size for an integer is

```
-2147483648 to +2147483647
```

For this particular bill run we were trying to store a value of `2214000830`. So the generate summary was erroring at the point we were trying to save the result to PostgreSQL.

If we update the database fields to be bigint's then we'll have plenty of room

```
-9223372036854775808 to 9223372036854775807
```

This adds an additional problem though. The underlying postgres node driver returns these as strings!

So this change covers 2 things

- updating the database fields to be big ints
- ensuring that wherever we extract a billrun record the data is seen by the app as a number and not a string.

2020-10-17 20:17 UTC, Cruikshanks commented
Actually making a proper change on this one @StuAA78 hence the request for a review! 😁

2020-10-19 09:05 UTC, StuAA78 requested changes

2020-10-19 09:05 UTC, StuAA78 commented on app/models/bill_run.js
> +  convertBigInts (params) {
JS passes in a reference to an object instead of the actual object, so the changes to `params` made in this function are directly affecting the original `params` object. In this instance I don't think it really makes a difference to how this function works, however it would probably be cleaner to return a new object, eg:

```javascript
convertBigInts (params) {
  return {
    ...params,
    credit_value: parseInt(params.credit_value),
    invoice_value: parseInt(params.invoice_value),
    credit_line_value: parseInt(params.credit_line_value),
    debit_line_value: parseInt(params.debit_line_value),
    net_total: parseInt(params.net_total)
  }
}
```

2020-10-19 09:09 UTC, Cruikshanks commented on app/models/bill_run.js
> +  convertBigInts (params) {
Thanks for the lesson 😁 ! I assume this also would ensure the object I get back wouldn't contain 2 `credit_value` properties etc?

2020-10-19 09:27 UTC, StuAA78 commented on app/models/bill_run.js
> +  convertBigInts (params) {
That's right, you can put the same property into an object as many times as you like without error, it'll overwrite it each time and use the last one.

2020-10-19 10:04 UTC, StuAA78 approved these changes
👍

2020-10-19 10:09 UTC, merged